[build]
  base    = "./"
  command = "NODE_ENV=production yarn build && cp -rf ./src/extra-files/edge/. ./dist/"
  publish = "./dist/"

  [build.environment]
    NODE_ENV     = "development"
    NODE_VERSION = "10.13.0"
