[build]
  base    = "./"
  command = "NODE_ENV=production yarn build && cp -rf ./src/extra-files/edge/. ./dist/"
  publish = "./dist/"

  [build.environment]
    NODE_ENV     = "development"
    NODE_VERSION = "10.13.0"
    VUE_APP_URL  = "${URL}"

[context.deploy-preview.environment]
  VUE_APP_URL = "${DEPLOY_PRIME_URL}"
