[build]
  base    = "./"
  command = "yarn build && cp -rf ./src/extra-files/edge/. ./build/public/"
  publish = "./build/public/"

  [build.environment]
    NODE_ENV     = "development"
    NODE_VERSION = "10.13.0"
