[build]
  base    = "./"
  command = "yarn build --prod --progress false && cp -rf ./src/extra-files/edge/. ./dist/neru-camera/"
  publish = "./dist/neru-camera/"

  [build.environment]
    NODE_ENV     = "development"
    NODE_VERSION = "10.13.0"
