[build]
  base    = "./"
  command = "NODE_ENV=production yarn build --aot --prod --progress false"
  publish = "./dist/neru-camera/"

  [build.environment]
    NODE_ENV     = "development"
    NODE_VERSION = "8.12.0"
