name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn format-check
      - run: yarn lint
      - if: startsWith(github.ref, 'refs/tags/v')
        env:
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel -S ${VERCEL_SCOPE} -c -t ${VERCEL_TOKEN} --prod
