name: 不具合報告
description: 改善に役立つ報告をする。
labels: [bug]
body:
  - type: input
    attributes:
      label: 不具合の詳細
      description: 不具合について簡潔でわかりやすい説明をしてください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 再現手順
      description: 不具合を再現する手順を書いてください。
      placeholder: |
        1. 「...」を開く
        2. 「...」をクリックする
        3. 「...」までスクロールする
        4. エラー発生!
      value: |
        1. 
        2. 
        3. 
        ...
      render: markdown
    validations:
      required: false
  - type: input
    attributes:
      label: 期待する挙動
      description: あなたが期待する挙動について簡潔でわかりやすい説明をしてください。
    validations:
      required: false
