blank_issues_enabled: true
contact_links:
  - about: このプロジェクトにアイデアの提案をする。
    name: 機能要望
    url: https://github.com/inabagumi/inaba-jinja/discussions/new?category=ideas
  - about: 質問や連絡はTwitterでお受けしております。
    name: Twitter
    url: https://twitter.com/Inaba_Jinja
