version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10.15.3

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/
      - persist_to_workspace:
          paths:
            - ./*
          root: .

  lint:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint

  build:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          paths:
            - ./docs/.vuepress/dist/
          root: .

  publish:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: |
          yarn deploy \
            --repo https://${GITHUB_TOKEN}@github.com/inabagumi/website.git \
            --user 'Neru bot <bot@haneru.dev>' \
            > /dev/null

workflows:
  version: 2

  workflow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - lint
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
