version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:8.12.0-browsers
    environment:
      - NODE_ENV: development
    working_directory: ~/project

commands:
  yarn_install:
    steps:
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-

      - run:
          command: yarn install --frozen-lockfile
          name: yarn install

      - save_cache:
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
      - run: yarn lint
      - run:
          command: yarn test --browsers ChromeHeadlessCI --progress false --watch false
          name: yarn test
      - run:
          command: yarn e2e --configuration=ci
          name: yarn e2e
      - run: yarn build --progress false

  deploy:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
      - run: yarn build --aot --prod --progress false
      - run: npx firebase-tools deploy --token ${FIREBASE_TOKEN}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+(?:\.\d+){0,2}$/
            branches:
              ignore: /.*/
