name: Deploy

on:
  pull_request:
    branches:
      - '!*'
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy to Vercel
        run: npx vercel -S ${VERCEL_SCOPE} -c -t ${VERCEL_TOKEN} --prod
        env:
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
