name: Release

on:
  pull_request:
    branches:
      - '!*'
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Create GitHub Release
        run: yarn conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Now
        run: npx now -S ${NOW_SCOPE} -c -t ${NOW_TOKEN} --prod
        env:
          NOW_SCOPE: ${{ secrets.NOW_SCOPE }}
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
